
# Copyright (C) PhcNguyen Developers
# Distributed under the terms of the Modified BSD License.

class AlgorithmTypes:
    @staticmethod
    def generate_id(string: str) -> str:...
    def handle_data(self, client_address: tuple, data: dict) -> bytes:...


class NetworksTypes:
    def start(self):...
    def stop(self):...
    def accept_connections(self):...
    def handle_client(self, client_socket, client_address: tuple):...
    def set_message_callback(self, callback):...
    def _notify(self, message):...
    def _notify_data(self, message):...
    def _notify_error(self, message):...